@isTest 
private class AA_TBN_CaseEntry_FileUploadTest {

    static testMethod void myUnitTest() {
        Apexpages.currentPage().getParameters().put('Success', 'Success');
        TBN_CaseEntry_FileUpload controller = new TBN_CaseEntry_FileUpload();
        controller.insertContent();
        }
        
    static testMethod void myUnitTest2() {
        TBN_CaseEntry_FileUpload controller = new TBN_CaseEntry_FileUpload();
        controller.insertContent();
        }
        
    static testMethod void myUnitTest3() {
        TBN_CaseEntry_FileUpload controller = new TBN_CaseEntry_FileUpload();
        controller.objAttachment.body = blob.valueOf('Test');
        controller.objAttachment.Name = 'Test';
        controller.insertContent();
        }        
}